name: vbooks_source
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.19.0
  shared_preferences: ^2.1.0
  flutter_typeahead: ^4.0.0
  provider: ^6.1.2
  flutter_otp_text_field: ^1.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - assets/images/product/
    - assets/images/spy.png
    - assets/breathingroom.jpg
    - assets/mockingbird.jpg
