name: vbooks_source
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_typeahead: ^4.0.0
  provider: ^6.1.2
  flutter_otp_text_field: ^1.1.3+2
  flutter_native_splash: ^2.4.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - assets/images/product/chinhtri/
    - assets/images/product/kinangsong/
    - assets/images/product/kinhdi/
    - assets/images/product/kinhte/
    - assets/images/product/nuoidaycon/
    - assets/images/product/sachgiaokhoa/
    - assets/images/product/sachthieunhi/
    - assets/images/product/tamly/
    # - assets/images/product/trinhtham/
    - assets/images/product/truyentranh/
    - assets/images/product/vanhoc/
    - assets/images/spy.png
    - assets/breathingroom.jpg
    - assets/mockingbird.jpg

flutter_native_splash:
  android: true
  background_image: "assets/images/splash.jpg"
